FROM busybox
MAINTAINER manote.n@g-able.com

# setup UID which is to run container
USER manote

# This is my work dir in image
WORKDIR /home/manote

#copy file from host to image 
COPY local-file.txt .

